### ISSUE TITLE
Error found while trying to compile under Ubuntu 18.04

### ISSUE THREAD

**Issue by jsalvatm** [Robotips/uConfig#10]
Hello,
I cloned uConfig, installed qt5 as indicated and tried to compile it. The result was a missing header file:

../../src/pdf_extract/datasheet.cpp:28:10: fatal error: poppler/qt5/poppler-qt5.h: File not found
 #include <poppler/qt5/poppler-qt5.h>

However command: qmake -query QT_VERSION
reported
5.9.5

I tried to find that specific file without success. Do I need to install an additional qt package?

**Comment by sebcaux** [comment]
Hello,
As mentionned in README, you also need to install qt poppler :

`sudo apt install libpoppler-qt5-dev`

This will install the poppler lib with qt binder and dev files.

**Comment by jsalvatm** [comment]
Now it compiles. I apologize. I'm completely new to qt and I thought poppler was part of it.

Thanks for your quick answer
Joan
