### ISSUE TITLE
App crashes if microchip.kss isn't found

### ISSUE THREAD

**Issue by fjrg76mx** [Robotips/uConfig#12]
As new user of your great app I tried this directly and I got a segment violation:

```
$ ~/uConfig-master/bin/uconfig LPC84x.pdf -o lpc84x.lib -r microchip.kss
> LPC84x.pdf
4 packages extracted, saved in lpc84x.lib
Violación de segmento (`core' generado)
```
Although it says the library was created, it wasn't. However it did work without such option:

```
$ ~/uConfig-master/bin/uconfig LPC84x.pdf -o lpc84x.lib 
> LPC84x.pdf
4 packages extracted, saved in lpc84x.lib
Elapsed time: 1087ms
$
```
I haven't seen the results yet, I wanted you to know this little issue. My workstation is based upon Linux Mint 19, Cinnamon, 64B.

Out of context: Why this program isn't included by default with Kicad?

**Comment by sebcaux** [comment]
Thanks for the issue !
It was worst than a segfault when the file does not exist, the option -r simply segfault...
Anyway it is fixed now !
