### ISSUE TITLE
Bar and Family name

### ISSUE THREAD

**Issue by MahmodSbry** [Robotips/uConfig#14]
First I need to thank you for your amazing tool, I have along time for searching on tool like that. Tank you again.
Second, For The image you upload to show the output https://github.com/Robotips/uConfig/blob/master/uConfig_gui.png
Some pins have Bar in its name and this image showing that you already extracted it. But It does not work for me, just extract pin name without the bar.
Also, your image show that you get the family name(Name) but for me it get "packx" where x refer to package name.
So, Please send me the last version from your tool.

**Comment by sebcaux** [comment]
You have the latest version. This picture is done by opening an existing library from kicad official libs.

When you extract component from pdf, everithings is not done automatically :  You need to set the name of each component and to add tildes arround part of name that have a bar.

This tool only save you 95% of your time :)

**Comment by sebcaux** [comment]
Not actually, but maybe one day in a far future...
