### ISSUE TITLE
EAGLE export?

### ISSUE THREAD

**Issue by martonmiklos** [Robotips/uConfig#18]
Hi @sebcaux 

Many thanks for sharing this project, it is very promising and smart tool!

I have some Qt classes (generated from the XML descriptors) which can be used to parse/generate design/library files for the Autodesk EAGLE.

Would you accept a patch for the uConfig which would allow saving to EAGLE library files?

**Comment by sebcaux** [comment]
Hi @martonmiklos,

I realize that I don't give feedback to your request, I'm very sorry... I have very few times to give to this project at the moment.

It's a good idea, I'm now open to give access to this tool to closed source tools like EAGLE.

I imagine we can add https://github.com/martonmiklos/qt_eagle_xml_parser as submodule in uConfig repo and create a system of abstart class to import/export to various format like CSV, excel, EAGLE, Altium...

**Comment by martonmiklos** [comment]
Hi @sebcaux,
No worries! Yes I thought about the same approach. I might came up with  PR soon!

**Comment by sebcaux** [comment]
Trying to remember the structure of project...

Finally, I already prepare for multiple format import/export library. In kicad/parser/, LibParser is an injterface to provide multiple implementation of loadLib and saveLib.

**Comment by GravisZro** [comment]
This is a moot point now since [Eagle is dead.](https://www.autodesk.com/products/fusion-360/blog/future-of-autodesk-eagle-fusion-360-electronics/)

This issue can be closed.

**Comment by martonmiklos** [comment]
> This is a moot point now since [Eagle is dead.](https://www.autodesk.com/products/fusion-360/blog/future-of-autodesk-eagle-fusion-360-electronics/)
> 
> This issue can be closed.

Yes indeed! Long live Kicad!
