### ISSUE TITLE
C++11?

### ISSUE THREAD

**Issue by martonmiklos** [Robotips/uConfig#19]
Hi @sebcaux 

What is your standpoint regarding to using C++11 only features (nullptr, range based for, etc) in the code?

I would love to rely on these features, most modern compilers supporting it. Enforcing it is easy in the pro file.

**Comment by martonmiklos** [comment]
@sebcaux  ping!

If I got a yes/no answer I can finalize #20 and #17

**Comment by sebcaux** [comment]
I'm OK to add C++11, but not by parts.
Add your code with C++11 and wee will pass the existing parts later.
