### ISSUE TITLE
invalid brew option

### ISSUE THREAD

**Issue by sslupsky** [Robotips/uConfig#22]
I attempted to install uConfig following the instructions for macOS.  The instructions say to install poppler using brew with the --with-qt command line option.  Unfortunately, --with-qt is not a valid brew command line option.  Is this a typo?

Error: invalid option: --with-qt

**Comment by martonmiklos** [comment]
It seems that all options had been removed from the homebrew:
https://github.com/Homebrew/homebrew-core/issues/31510

Anyway it looks like the Qt binding is enabled in that poopler brew formulae:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/poppler.rb#L45
so it is possible that just leaving out that argument will build a proper poppler build.

**Comment by martonmiklos** [comment]
I can confirm that I have managed to build it on travis without the --with-qt option successfully. 
@sslupsky could you please do a build and try out that the uConfig actually working?
If yes then I can PR the removal of the option from the docs and the .travis.yml

**Comment by martonmiklos** [comment]
@sebcaux I have seen that you are working on it, check the links above (in the case if you have not seen them) and just remove the --with-qt argument.
