### ISSUE TITLE
snap package available in store

### ISSUE THREAD

**Issue by ppd1990** [Robotips/uConfig#24]
Hi,

I packaged your great tool as a snap package and pushed it to the snap store:
https://snapcraft.io/uconfig

Packaging is here:
https://github.com/ppd1990/uconfig-snap

Makes it a little easier to be installed on Ubuntu (and others).

Cheers
Max

**Comment by sebcaux** [comment]
Hi,
Thanks for this amazing job, great idea.
If some parts of the tools needs some improvement to be packaged, feel free to contact me.
Cheers,
Seb

**Comment by ppd1990** [comment]
I have a few ideas:
- Provide install option/target in qmake so one can do ```make install``` afterwards. I believe this is missing and so I provided this step in the snap. However I have no experience with qmake and so it might be the snapcraft qmake plugin that does something wrong
- SVG logo. The currently packaged one looks a bit rough
- A few more coherent sentences to describe the package. Those could appear in the README.md too.
- A desktop file is a must. I threw something together in the snap package. Maybe we could upstream this and enhance it a little. This could also be added to a qmake install target.
- a new release at some point would be nice. I'd be comfortable pushing that to the "stable" channel in the store. Atm it's in the "edge" channel

Maybe I'll tackle a few of those myself, if time allows it.

**Comment by ppd1990** [comment]
You could also add this button to the project:

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/uconfig)

markdown here:
```
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/uconfig)
```
