### ISSUE TITLE
Premade windows build (Qt5PrintSupport.dll) missing

### ISSUE THREAD

**Issue by Phara0h** [Robotips/uConfig#3]
when trying to run any of the premade binaries on windows 10 it complines "Qt5PrintSupport.dll" not being found. I went ahead and downloaded QT5 and it still does not work.

**Comment by sebcaux** [comment]
Hi, thanks for the issue.
The premade version of poppler works with Qt5.2 but not with newest.
I need time to compile a proper version of poppler with Qt 5.9.

**Comment by Phara0h** [comment]
Can't wait to use this but the new commit "Fixed win binaries distribution #3 and Fixed win binaries zip creation #3" did not fix the issue for me. I still get the missing "Qt5PrintSupport.dll" and now I get another error saying it is also missing "Qt5Xml.dll"
