### ISSUE TITLE
Loading badly generated library crashes application

### ISSUE THREAD

**Issue by ThudPoland** [Robotips/uConfig#30]
I've generated library with command:
_uconfig 70005208d.pdf -o dsPIC.lib -r microchip.kss_
Then i've tried to open this in uconfig_gui.
It crashed.
I've checked generated file. It contained doubled *p.3_pack0* and *p.4_pack0* sections.
This can be also another bug. 

Datasheet:
http://ww1.microchip.com/downloads/en/DeviceDoc/70005208d.pdf
Expected:
There should be error message in gui.
Generated sections should be:
*p.3_pack0*, *p.3_pack1*, *p.4_pack0*, *p.4_pack1*

Linux 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
uConfig: Build date: Sep 26 2019 time: 18:21:35
Installed by snap.

**Comment by sebcaux** [comment]
What is craching ? uconfig_gui ?
Could you give me the scenario that reproduce the crash ?

Thank you for your interrest

**Comment by ThudPoland** [comment]
So - uconfig_gui is crashing.

Here is scenario:
1. Generate file with:
uconfig 70005208d.pdf -o dsPIC.lib -r microchip.kss (I've did this beacuse snap version of uconfig does not have any additional rules)
2. Open uconfig_gui
3. Load dsPIC.lib (this should crash uconfig_gui)

**Comment by sebcaux** [comment]
It was two bugs : 
* The smallest one was the pac number in pdf extraction was not increased in normal mode (not debug)
* The second one was inside the library list sorter (numericalsortfilterproxymodel) when all fiels were egual, a very stange seg fault appears
Good issue !
