### ISSUE TITLE
Unable to use KSS, missing info?

### ISSUE THREAD

**Issue by Spirit532** [Robotips/uConfig#35]
There's no clear explanation on how to use KSS on Windows.
I've tried placing a regex filter:
```
[P][A-L][0-9]+ {
    class: "gpio\1";
    elecType: bidir;
}
```
Into the textbox below the pin list and clicking "organize", but nothing happens. Selected different pins, and confirmed the regex actually works in the "pin name filter" search box at the very top.

Tried placing the .kss files in every directory, including next to the executable, as well as creating a "rules" directory. No results either.

Is it not supposed to work?

**Comment by sebcaux** [comment]
I know, it is not very clear at the moment.
The list of kss files appears in the list close to the Organize button. "package" means it just sort the pins by pin number. All the others items of list correspond to a kss file into 'rules' directory.
After choosing a kss file, you can edit it in the text editor below the pin list. Be carreful, changes are not saved.
![image](https://user-images.githubusercontent.com/17829909/70420635-7203e400-1a68-11ea-80a0-ff639c52034e.png)

If you have any ideas to improve the interface for that, please tell me.

**Comment by Spirit532** [comment]
The kss files are not detected when placed in the "rules" directory next to the executable on Windows.

**Comment by sebcaux** [comment]
The install dir should have the following structure : 

+ uConfig dir/
  * bin
    + uconfig.exe
  * rules
    + f1.kss
    + f2.kss

**Comment by Spirit532** [comment]
That fixes the issue. See if you can fix the build structure for windows - right now there's no top level directory or bin, it's just uconfig.exe with everything thrown in.
Should also be helpful to include the standard rule set in the release.

**Comment by sebcaux** [comment]
In the zip file https://ci.appveyor.com/api/projects/sebcaux/uconfig/artifacts/uconfig-win32-v0.zip, given on the readme page, the zip contains a top uconfig dir. Inside, you should find the right directories structure. Am I wrong ?

**Comment by Spirit532** [comment]
I must have missed this, since I usually assume these structures are just the defaults that the build system throws out, my bad.
A notice in the readme explaining where the kss files should go is all that's needed then!

**Comment by sebcaux** [comment]
Do not hesitate to do a pull request !
Thanks for your interest.
