### ISSUE TITLE
OSX compiling fails after too many errors

### ISSUE THREAD

**Issue by zelisse** [Robotips/uConfig#38]
I'm running OSX Catalina 10.15.4, Xcode 11.4 (11E146).

qt version 5.14.1
poppler 0.87.0

make -j4 gives the following errors/warnings, see below.

I would really like to use this program, can you please advise what to do to get it compiling on OSX?

Thank you very much for your help.

JK

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -O3 -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC -DKICAD_EXPORT_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../../kicad -I. -I/usr/local/Cellar/qt/5.14.1/lib/QtPrintSupport.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.14.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.14.1/lib -o drawpoly.o ../../../kicad/model/drawpoly.cpp
../../../kicad/model/pad.cpp:129:10: warning: comparison of two values with different enumeration types in switch statement
      ('Pad::Shape' and 'Pad::Type') [-Wenum-compare-switch]
    case Pad::Hole:
         ^~~~~~~~~
../../../kicad/model/pad.cpp:127:10: warning: comparison of two values with different enumeration types in switch statement
      ('Pad::Shape' and 'Pad::Type') [-Wenum-compare-switch]
    case Pad::Conn:
         ^~~~~~~~~
../../../kicad/model/pad.cpp:125:10: warning: comparison of two values with different enumeration types in switch statement
      ('Pad::Shape' and 'Pad::Type') [-Wenum-compare-switch]
    case Pad::Smd:
         ^~~~~~~~
../../../kicad/model/pad.cpp:123:10: warning: comparison of two values with different enumeration types in switch statement
      ('Pad::Shape' and 'Pad::Type') [-Wenum-compare-switch]
    case Pad::Std:
         ^~~~~~~~
[ --- snip ---]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -O3 -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC -DKICAD_EXPORT_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../../kicad -I. -I/usr/local/Cellar/qt/5.14.1/lib/QtPrintSupport.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.14.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.14.1/lib -o rulesparser.o ../../../kicad/pinruler/rulesparser.cpp
../../../kicad/itemmodel/componentpinstableview.cpp:190:35: warning: 'toList' is deprecated: Use values() instead.
      [-Wdeprecated-declarations]
    emit pinSelected(selectedPins.toList());
                                  ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qset.h:250:5: note: 'toList' has been explicitly marked deprecated here
    Q_DECL_DEPRECATED_X("Use values() instead.")
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qcompilerdetection.h:676:55: note: expanded from macro
      'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
1 warning generated.

[--- snip ---]
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:43:
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qtguiglobal.h:52:13: warning: 'Q_GUI_EXPORT' macro redefined
      [-Wmacro-redefined]

[--- snip ---]
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:43:
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qtguiglobal.h#    define Q_GUI_EXPORT Q_DECL_IMPORT:
52:13            ^:
 /usr/local/include/QtCore/qglobal.h:1561:13:0;1;35m warning: note: previous definition 'Q_GUI_EXPORT'is  macrohere redefined

      [-Wmacro-redefined]
#    define Q_GUI_EXPORT
            ^
#    define Q_GUI_EXPORT Q_DECL_IMPORT
            ^
/usr/local/include/QtCore/qglobal.h:1561:13: note: previous definition is here
#    define Q_GUI_EXPORT

[--- snip ---]
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/QRectF:1:
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:77:5: In file included from error../../../pdf_extract/datasheetbox.cpp: :19:
In file included from ../../../pdf_extract/datasheetbox.hunknown: 24type:
 In file included from name/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/QRectF :'Q_DECL_RELAXED_CONSTEXPR'1:

/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:77:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setLeft(int pos) noexcept;
    ^
    Q_DECL_RELAXED_CONSTEXPR inline void setLeft(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:78:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setTop(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:78:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setTop(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:79:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:79:5: error: unknown type    Q_DECL_RELAXED_CONSTEXPR inline void setRight(int pos) noexcept;
name     ^'Q_DECL_RELAXED_CONSTEXPR'

    Q_DECL_RELAXED_CONSTEXPR inline void setRight(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:80:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h
:80:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setBottom(int pos) noexcept;
    ^
    Q_DECL_RELAXED_CONSTEXPR inline void setBottom(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:81:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setX(int x) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:81:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setX(int x) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:82:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setY(int y) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:82:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setY(int y) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h84::845::5 : error: error: unknown typeunknown  nametype  'Q_DECL_RELAXED_CONSTEXPR'name
'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setTopLeft(const QPoint &p) noexcept;    Q_DECL_RELAXED_CONSTEXPR inline void setTopLeft(const QPoint &p) noexcept;

    ^
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:85:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setBottomRight(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:85:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setBottomRight(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:86:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setTopRight(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:86:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setTopRight(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:87:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setBottomLeft(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:87:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void setBottomLeft(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:95:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveLeft(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:95:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveLeft(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:96:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveTop(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:96:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveTop(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:97:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveRight(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:97:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveRight(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:98:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveBottom(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:98:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveBottom(int pos) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:99:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveTopLeft(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:99:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveTopLeft(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:100:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveBottomRight(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:100:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveBottomRight(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:101:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveTopRight(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:101:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveTopRight(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:102:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveBottomLeft(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:102:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveBottomLeft(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:103:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveCenter(const QPoint &p) noexcept;
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qrect.h:103:5: error: unknown type name 'Q_DECL_RELAXED_CONSTEXPR'
    Q_DECL_RELAXED_CONSTEXPR inline void moveCenter(const QPoint &p) noexcept;
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
fatal error: too many errors emitted, stopping now [-ferror-limit=]

[--- snip ---]
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:47:
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:95:26: error: expected ')'
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
                         ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:95:25: note: to match this '('
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
                        ^
In file included from ../../../pdf_extract/datasheetpackage.cpp:19/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:
:In file included from 95../../../pdf_extract/datasheetpackage.h::5124::
 In file included from ../../../pdf_extract/../kicad/model/component.h:error24: :
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/QImageexpected: 1')':
In file included from
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:47:
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:95:26: error:     Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
expected                                                  ^
 ')'/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h
:95:20: note: to match this '('
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
                         ^
                   ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:95:25: note: to match this '('
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
                        ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:95:51: error: expected ')'
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
                                                  ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:95:20: note: to match this '('
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
                   ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h::9595::55::  errorerror: : C++C++  requiresrequires  aa  typetype  specifierspecifier  forfor  allall

            declarationsdeclarations

    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == uint(TotalFieldWidthByOffsets));    ^

    ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:96:26: error: /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:expected96 :')'26:
 error: expected ')'
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));
                         ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:96:25    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));:
                          ^
note: to /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.hmatch: 96this: 25'(':
note: to match this '('
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));
                        ^
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h
:96                        ^:
51: error: expected /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h')':96
:51: error: expected ')'
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));
                                                  ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:96:20: note:     Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));
to                                                   ^match
 this /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h'(':96
:20: note: to match this '('
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));
                   ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:96:    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));5
:                    ^
error: C++ requires a/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h :type96 :specifier5 :for  all
error      : declarations
C++ requires a type specifier for all
      declarations    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));

    ^
    Q_STATIC_ASSERT(uint(TotalFieldWidthByWidths) == 8 * sizeof(quint64));
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:225:12: error: unknown type name 'Q_DECL_CONST_FUNCTION'
    friend Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline bool operator==(QPixelFormat fmt1, QPixelFormat fmt2)
           ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:225:12: error: unknown type name 'Q_DECL_CONST_FUNCTION'
    friend Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline bool operator==(QPixelFormat fmt1, QPixelFormat fmt2)
           ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:228:12: error: unknown type name 'Q_DECL_CONST_FUNCTION'
    friend Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline bool operator!=(QPixelFormat fmt1, QPixelFormat fmt2)
           ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h:228:12: error: unknown type name 'Q_DECL_CONST_FUNCTION'
    friend Q_DECL_CONST_FUNCTION Q_DECL_CONSTEXPR inline bool operator!=(QPixelFormat fmt1, QPixelFormat fmt2)
           ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qpixelformat.h::231231::11::  errorerror: : C++C++  requiresrequires  aa  typetype  specifierspecifier  forfor  allall

            declarationsdeclarations

Q_STATIC_ASSERT(sizeof(QPixelFormat) == sizeof(quint64));Q_STATIC_ASSERT(sizeof(QPixelFormat) == sizeof(quint64));

^^

20 errors generated.
make[1]: *** [datasheetpin.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../../../pdf_extract/datasheetpackage.cpp:19:
In file included from ../../../pdf_extract/datasheetpackage.h:24:
In file included from ../../../pdf_extract/../kicad/model/component.h:24:
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/QImage:1:
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:53:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not
      defined
#if QT_DEPRECATED_SINCE(5, 0)
    ^
In file included from ../../../pdf_extract/datasheet.cpp:19:
In file included from ../../../pdf_extract/datasheet.h:24:
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/QImage:1:
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:53:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not
      defined
#if QT_DEPRECATED_SINCE(5, 0)
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:58:1: error: unknown type name
      'Q_FORWARD_DECLARE_MUTABLE_CG_TYPE'
Q_FORWARD_DECLARE_MUTABLE_CG_TYPE(CGImage);
^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:76:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not
      defined
#if QT_DEPRECATED_SINCE(5, 0)
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:58:1: error: unknown type name
      'Q_FORWARD_DECLARE_MUTABLE_CG_TYPE'
Q_FORWARD_DECLARE_MUTABLE_CG_TYPE(CGImage);
^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:76:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not
      defined
#if QT_DEPRECATED_SINCE(5, 0)
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:139:5: error: unknown type name 'Q_ENUM'
    Q_ENUM(Format)
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:139:5: error: unknown type name 'Q_ENUM'
    Q_ENUM(Format)
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:139:/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h19::139 :19: error: error: expected expected';'  ';'at at end of declaration list
 end of declaration list
    Q_ENUM(Format)
                  ^
    Q_ENUM(Format)
                  ;                  ^
                  ;

/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h220::2205::5 : errorerror: : function-likefunction-like  macromacro  'QT_DEPRECATED_SINCE''QT_DEPRECATED_SINCE'  is isnot
not
defined      defined

#if QT_DEPRECATED_SINCE(5, 10)#if QT_DEPRECATED_SINCE(5, 10)

    ^    ^

/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:223:5: error: unknown type name 'qsizetype'; did you mean
      'QPolygonF::size_type'?
    qsizetype sizeInBytes() const;
    ^~~~~~~~~
    QPolygonF::size_type
/usr/local/include/QtCore/qvector.h:280:17: note: 'QPolygonF::size_type' /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.hdeclared: 223here:5
: error:     typedef int size_type;
                ^unknown
 type name 'qsizetype'; did you mean
      'QPolygonF::size_type'?
    qsizetype sizeInBytes() const;
    ^~~~~~~~~
    QPolygonF::size_type
/usr/local/include/QtCore/qvector.h:280:17: note: 'QPolygonF::size_type' declared here
    typedef int size_type;
                ^
In file included from ../../../pdf_extract/datasheetpackage.cpp:19:
In file included from ../../../pdf_extract/datasheetpackage.h:24:
In file included from ../../../pdf_extract/../kicad/model/component.h:24:
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/QImage:1:
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:322:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not
      defined
#if QT_DEPRECATED_SINCE(5, 0)
    ^
In file included from ../../../pdf_extract/datasheet.cpp:19:
In file included from ../../../pdf_extract/datasheet.h:24:
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/QImage:1:
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:322:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not
      defined
#if QT_DEPRECATED_SINCE(5, 0)
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:347:33: error: expected ';' at end of declaration list
    CGImageRef toCGImage() const Q_DECL_CF_RETURNS_RETAINED;
                                ^
                                ;
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:350:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not
      defined/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:
347:33: #if QT_DEPRECATED_SINCE(5, 0)error
:     ^
expected ';' at end of declaration listfatal error:
too many errors emitted, stopping now [-ferror-limit=]
    CGImageRef toCGImage() const Q_DECL_CF_RETURNS_RETAINED;
                                ^
                                ;
/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers/qimage.h:350:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not
      defined
#if QT_DEPRECATED_SINCE(5, 0)
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[1]: *** [datasheetpackage.o] Error 1
20 errors generated.
make[1]: *** [datasheetbox.o] Error 1
1 warning and 20 errors generated.
make[1]: *** [datasheet.o] Error 1
make: *** [sub-pdf_extract-make_first-ordered] Error 2

**Comment by sebcaux** [comment]
Could you please try this : https://stackoverflow.com/questions/55393028/cmake-qt-vtk-compilation-errors-in-macos-mojave
I don't think these errors comes from uConfig

**Comment by zelisse** [comment]
It now works! Thank you very much for your quick response.
