### ISSUE TITLE
does not compile under linux

### ISSUE THREAD

**Issue by nopeppermint** [Robotips/uConfig#46]
I am getting a lot of warning/error

```

/usr/lib/qt5/bin/qmake -o Makefile ../../src/uconfig_gui/uconfig_gui.pro
WARNING: Failure to find: ../../contrib/QDarkStyleSheet/qdarkstyle/style.qrc
/usr/lib/qt5/bin/rcc: File does not exist '../../contrib/QDarkStyleSheet/qdarkstyle/style.qrc'
^Cmake: *** [Makefile:181: sub-uconfig_gui-make_first-ordered] 

```

**Comment by nopeppermint** [comment]
problem was missing, not updated submodule

=> git submodule init
=> git submodule update

needed before creating the build directory

**Comment by sebcaux** [comment]
You're right.
You need to init submodule or clone uConfig with --recursive option.
I should add it clearly in the Readme file.
