### ISSUE TITLE
Infineon datasheet extraction issue (100 pins from table)

### ISSUE THREAD

**Issue by mxa** [Robotips/uConfig#58]
**Describe the bug**
There is no graphic in the datasheet, just a table for different package sizes, uConfig can't find anything usable in the datasheet.

**Datasheet identification**
https://www.infineon.com/dgdl/Infineon-CY8C41xx_PSoC_4_MCU_PSoC_4100S_Max_Based_on_Arm_Cortex_-M0_CPU-DataSheet-v07_00-EN.pdf?fileId=8ac78c8c83cd30810183fc2ad1424e75

**Screenshots**
![grafik](https://github.com/Robotips/uConfig/assets/1220707/018c5bba-7123-49b3-b815-ee0d0188f478)

**Desktop (please complete the following information):**
 - OS: [Kubuntu]
 - Version [23.10]
 - Qt Version: [5 and 6]

**Comment by sebcaux** [comment]
Hi,
There are two issues with this datasheet : 
* uConfig is not able to read table with multiple packages
* uConfig is not able to read one package on multiple page

These two features are planned for some day...

But I could recommend you to move data to a CSV file and create schematics component with uConfig, it will save you a lot of time.

**Comment by mxa** [comment]
Is this feature implemented yet? 
![grafik](https://github.com/Robotips/uConfig/assets/1220707/7c453cd7-21ec-485e-a437-d9af3098cf0d)

**Comment by sebcaux** [comment]
Yes since af13966e28d22b778a06ece2cf77a99801f89d96

**Comment by mxa** [comment]
ok, I downloaded the snap after I could not compile it straight away, but "latest/edge" is from 12 April 2021. Anyway, I was almost done with the 100 pins, so I just finished it manually.
