### ISSUE TITLE
Missing datasheet_extractor_common.h file

### ISSUE THREAD

**Issue by martonmiklos** [Robotips/uConfig#6]
Hi there,

The qmake throws warning when building the project: there is a reference in the pdf_extract.pro to a file which is not in the repo:
https://github.com/Robotips/uConfig/blob/master/src/pdf_extract/pdf_extract.pro#L31

Not a big deal it starts the building, since I got to the linking phase.

**Comment by sebcaux** [comment]
Thanks, I just fixed it, it was a problem of renamed header non integrated in the pro file.
Have a good test !
